### ISSUE TITLE
Feature request: SPO2 Continuous Data

### ISSUE THREAD

**Issue by stunami3** [James-2879/OuraAppleHealth#10]
Hey, just stumbled upon your shortcuts, which are great, and was wondering if you could make an SPO2 continuous version similar to the HRV.

**Comment by James-2879** [comment]
Oura API doesn't provide access to more granular SPO2 data unfortunately, only the nightly average. I am aware the app shows you recorded 'breathing disturbances' over the night, but there is no accessible blood oxygen data attached to this. If this data becomes available in the future then I will definitely revisit this idea.

**Comment by stunami3** [comment]
Makes sense, thanks!
