### ISSUE TITLE
RHR shortcut logs HRV

### ISSUE THREAD

**Issue by joakimskog** [James-2879/OuraAppleHealth#2]
It seems like my RHR shortcut enter my HRV instead of lowest_heart_rate. In the script, it collects lowest_heart_rate, but in the next step it says "set rhr to value Heart Rate Variability". In the last step of the RHR shortcut, it logs "Resting heart rate" to Health, with the variable "rhr".

(My phone is set to Swedish language so the English translation might not be exact.)

**Comment by James-2879** [comment]
The RHR shortcut is copied from the HRV shortcut as a template, but the magic variables just haven't updated their names. For some reason it is not possible to force a name change, as Apple automatically defined the name when I wrote the HRV shortcut. If you check your Apple Health data, you will see that RHR is correctly being pulled. I understand the confusion, though.
