### ISSUE TITLE
One shortcut to run all 4 shortcuts?

### ISSUE THREAD

**Issue by aintnogeek** [James-2879/OuraAppleHealth#4]
Maybe you can create one that runs all 4 of them as one - HRV, RHR, SPO2, TEMP?

**Comment by adrian-fuertes** [comment]
I don't think this would be wise, it creates extra overhead to keep them all up to date plus it will eat into the runtime of the shortcut. You can easily accomplish this yourself by creating a shortcut and utilizing the `run shortcut` action, which gives you the ability to run an arbitrary amount of shortcuts at sequentially

**Comment by James-2879** [comment]
This is something I purposefully didn't do, simply because as @adrian-fuertes mentioned if I make a small update to one I would also have to update the 'master' shortcut.

Also separate shortcuts means that if one shortcut errors for whatever reason, the others won't be directly affected.
