### ISSUE TITLE
Continuous HRV shortcut issue

### ISSUE THREAD

**Issue by itscaionotkyle** [James-2879/OuraAppleHealth#7]
When I run the continuous HRV shortcut, the data gets written into Apple Health starting from 12:05PM from the previous day.

I'm not sure if the shortcut is pulling the correct data and writing it into the wrong timing, or if it's pulling the wrong data altogether.

I'm inclined to think it's writing to the wrong timing mostly because I dont wear the ring during the day, so I'm not sure how Oura would have any measurements of my HRV at 12pm.

**Comment by exhibiton** [comment]
I noticed this as well myself when I changed timezones. It seems like Shortcuts has issues transforming full ISO8601 strings to dates so I needed to do some manual string formatting to remove seconds seconds and milliseconds to fix this. I'll put up a Pull Request to fix it.

**Comment by James-2879** [comment]
@exhibiton Thanks for the fix

**Comment by itscaionotkyle** [comment]
@exhibiton  @James-2879 Thanks for the update! I ran it and worked very well on my end, you guys rock! FYI that the new Continuous HRV shortcut was uploaded with someone's API key attached to it. Might want to remove that, or regenerate a new code haha

**Comment by James-2879** [comment]
@itscaionotkyle Glad it works, and good spot on the key, I missed that - thanks! @exhibiton I pushed a version without the key and updated the link, but I haven't rebased it to remove the previous commit as I don't have access to a CLI at the moment. Maybe you want to rebase and make a PR, but probably better to revoke the key anyway
